CREATE INDEX GFGO_CORRELATIONOBJECTLINK$C0 ON GFGO_CORRELATIONOBJECTLINK(idA3A5)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX GFGO_CORRELATIONOBJECTLINK$C1 ON GFGO_CORRELATIONOBJECTLINK(idA3B5)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
