CREATE INDEX CorrelationObjectLink$COMPOS0 ON CorrelationObjectLink(idA3A5)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX CorrelationObjectLink$COMPOS1 ON CorrelationObjectLink(idA3B5)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
