ALTER TABLE APPO_CORRELATIONOBJECTLINK ADD approvalOpinion VARCHAR2(600 BYTE);
ALTER TABLE APPO_CORRELATIONOBJECTLINK ADD remark VARCHAR2(4000 BYTE);
ALTER TABLE APPO_CORRELATIONOBJECTLINK MODIFY aadDescription VARCHAR2(4000);